[package]
name = "helmci"
version = "0.3.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.4.13", features = ["derive"] }
serde = { version = "1.0.194", features = ["derive"] }
serde_yaml = "0.9.30"
serde_json = "1.0.111"
log = { version = "0.4.20", features = ["std"] }
lazy_static = "1.4.0"
tui = "0.19.0"
crossterm = { version = "0.27.0", features = ["event-stream"] }
tabled = "0.15.0"
tokio = { version = "1", features = ["full"] }
slack-morphism = { version = "1.16.1", features = ["hyper"] }
chrono = "0.4.31"
hyper-rustls = "0.25.0"
hyper = "1.1.0"
async-trait = "0.1.77"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
semver = "1.0.21"
url = "2.5.0"
futures = "0.3.30"
