[package]
name = "helmci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.0.26", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.9.14"
serde_json = "1.0.79"
log = { version = "0.4.14", features = ["std"] }
lazy_static = "1.4.0"
tui = "0.19.0"
crossterm = "0.25.0"
tabled = "0.10.0"
tokio = { version = "1", features = ["full"] }
slack-morphism = { version = "1.3.4", features = ["hyper"] }
chrono = "0.4.19"
hyper-rustls = "0.23.2"
hyper = "0.14.18"
async-trait = "0.1.53"
tracing = "0.1.5"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
semver = "1.0.16"
url = "2.2.2"
