[package]
name = "helmci"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.13", features = ["derive"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_yml = "0.0.11"
serde_json = "1.0.122"
log = { version = "0.4.22", features = ["std"] }
lazy_static = "1.5.0"
tui = "0.19.0"
crossterm = { version = "0.28.1", features = ["event-stream"] }
tabled = "0.16.0"
tokio = { version = "1", features = ["full"] }
slack-morphism = { version = "2.3.2", features = ["hyper"] }
chrono = "0.4.38"
hyper-rustls = "0.27.0"
hyper = "1.4.1"
async-trait = "0.1.81"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
semver = "1.0.23"
url = "2.5.2"
futures = "0.3.30"
hyper-util = "0.1.7"
tap = "1.0.1"
reqwest = { version = "=0.12.5", default-features = false, features = ["json", "rustls-tls"] }
nondestructive = "0.0.25"
