[package]
name = "helmci"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.3.19", features = ["derive"] }
serde = { version = "1.0.176", features = ["derive"] }
serde_yaml = "0.9.25"
serde_json = "1.0.104"
log = { version = "0.4.19", features = ["std"] }
lazy_static = "1.4.0"
tui = "0.19.0"
crossterm = { version = "0.26.1", features = ["event-stream"] }
tabled = "0.13.0"
tokio = { version = "1", features = ["full"] }
slack-morphism = { version = "1.14.0", features = ["hyper"] }
chrono = "0.4.26"
hyper-rustls = "0.24.1"
hyper = "0.14.27"
async-trait = "0.1.72"
tracing = "0.1.38"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
semver = "1.0.18"
url = "2.4.0"
futures = "0.3.28"
