[package]
name = "helmci"
version = "0.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_yml = "0.0.8"
serde_json = "1.0.117"
log = { version = "0.4.21", features = ["std"] }
lazy_static = "1.4.0"
tui = "0.19.0"
crossterm = { version = "0.27.0", features = ["event-stream"] }
tabled = "0.15.0"
tokio = { version = "1", features = ["full"] }
slack-morphism = { version = "2.2.0", features = ["hyper"] }
chrono = "0.4.38"
hyper-rustls = "0.26.0"
hyper = "1.3.1"
async-trait = "0.1.80"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
semver = "1.0.23"
url = "2.5.0"
futures = "0.3.30"
hyper-util = "0.1.4"
tap = "1.0.1"
reqwest = { version = "=0.12.4", default-features = false, features = ["json", "rustls-tls"] }
nondestructive = "0.0.21"
